рефакторинг 5 окончательный

diff --git a/bin/crab_syntax b/bin/crab_syntax
--- a/bin/crab_syntax
+++ b/bin/crab_syntax
@@ -44,58 +44,63 @@ error_msg=""
 
 echo_error(){
 	ERROR=$((ERROR+1))
-	echo "^^^ERROR $@"
+	echo -e "^^^ERROR $@"
 	echo
 	return 0
 }
 
-bash001(){
+hardbash001(){
 	### crab_indent
 	cp -f "$f" /tmp/crab_syntax_check.$$
 	chmod 666 /tmp/crab_syntax_check.$$
 	crab_indent /tmp/crab_syntax_check.$$ "$syntax_style" &>/tmp/crab_indent_out.$$
 	if ! cmp /tmp/crab_syntax_check.$$ "$f"; then
 		cat /tmp/crab_indent_out.$$
-		echo_error 'bash001 Не выполнен crab_indent'
+		echo_error 'hardbash001 Не выполнен crab_indent'
 	fi
 	rm -f /tmp/crab_indent_out.$$
 	rm -f /tmp/crab_syntax_check.$$
 	return 0
 }
 
-bash002(){
-	head -n 10 "$f" | grep -q '^set -eu' || echo_error 'bash002 Не установлен set -eu'
+hardbash002(){
+	if ! head -n 10 "$f" | grep -q '^set -euEo pipefail' \
+		&& ! grep -qm1 '::carbon.sys' "$f"; then
+		echo_error\
+			'hardbash002 Не установлен set -euEo pipefail '\
+			'как работать с pipefail: a|b|c|d || true '
+	fi
 	return 0
 }
 
-bash003(){
+hardbash003(){
 	egrep -n '^[^#].*(if|&&|\|\|).* \|\| true' "$f" &&\
-		echo_error 'bash003 Нельзя использовать || true в условных выражениях'
+		echo_error 'hardbash003 Нельзя использовать || true в условных выражениях'
 	return 0
 }
 
-bash004(){
+hardbash004(){
 	grep -n 'else' -A 1 "$f" | egrep "^[0-9$__SPACE-]*true" \
-		&& echo_error 'bash004 Нельзя использовать else true в условных выражениях'
+		&& echo_error 'hardbash004 Нельзя использовать else true в условных выражениях'
 	return 0
 }
 
-bash005(){
+hardbash005(){
 	### todo обрабатывать отдельно каждую функцию
 	count_func=$( grep '()[ ]*{' "$f" | wc -l || true ) # '
 	count_end_return=$( grep 'return' -A 1 "$f" | grep '^}' | wc -l || true )
 	[ $count_func != $count_end_return ] \
 		&& echo_error \
-		'bash005 $count_func!=$count_end_return В конце каждой функции должен быть '\
+		'hardbash005 $count_func!=$count_end_return В конце каждой функции должен быть '\
 		'return 0 или return $ret'
 	return 0
 }
 
-bash006(){
+hardbash006(){
 	if ! tail -n 2 "$f" | head -n 1 | grep -q 'SUCCESS'\
 		|| ! grep -q 'echo.*START' "$f"; then
 		grep -qm1 '::carbon.sys' "$f" && return 0
-		echo_error 'bash006 В начале каждого файла должен быть:
+		echo_error 'hardbash006 В начале каждого файла должен быть:
 		echo $0 START >&2
 		BODY
 		В конце каждого файла должен быть:
@@ -116,9 +121,9 @@ bash006(){
 	return 0
 }
 
-bash007(){
+hardbash007(){
 	if ! tail -n 1 "$f" | grep -q 'exit 0'; then
-		echo_error 'bash007 В конце каждого файла должен быть:
+		echo_error 'hardbash007 В конце каждого файла должен быть:
 		exit 0
 		или для библиотек:
 		# exit 0
@@ -127,33 +132,33 @@ bash007(){
 	return 0
 }
 
-bash008(){
+hardbash008(){
 	head -n 1 "$f" | grep -qm1 '#!/bin/bash' \
-		|| echo_error 'bash008 Обязательно использовать #!/bin/bash даже в include'
+		|| echo_error 'hardbash008 Обязательно использовать #!/bin/bash даже в include'
 	return 0
 }
 
-bash009(){
+hardbash009(){
 	grep -n 'let[^.]*=.*' "$f" \
 		&& echo_error \
-		'bash009 Нельзя использовать let тк дает ошибку при переходе через 0. Используйте $(())'
+		'hardbash009 Нельзя использовать let тк дает ошибку при переходе через 0. Используйте $(())'
 	return 0
 }
 
-bash010(){
-	cat "$f" | grep -v bash010 | grep -n '^[^#].*=/tmp/' \
-		&& echo 'WARNING ^^^ bash010 Не рекомендуется использовать переменные '\
+hardbash010(){
+	cat "$f" | grep -v hardbash010 | grep -n '^[^#].*=/tmp/' \
+		&& echo 'WARNING ^^^ hardbash010 Не рекомендуется использовать переменные '\
 		'для временных файлов, лучше /tmp/binname_tmpcat.$$'
 	if egrep -q '^[^#]rm.*/tmp/.*' "$f" && \
 		! egrep 'rm.*/tmp/.*' "$f" | grep -qm1 '$$'; then
 		egrep -n 'rm.*/tmp/.*' "$f"
-		echo_error 'bash011 Нельзя использовать временные файлы без $$, '\
+		echo_error 'hardbash011 Нельзя использовать временные файлы без $$, '\
 			'лучше rm -f /tmp/binname_tmpcat.$$'
 	fi
 	return 0
 }
 
-bash011(){
+hardbash011(){
 	indent_max=0
 	indent_max_lnum=0
 	local l=0
@@ -170,15 +175,15 @@ bash011(){
 	if (( $indent_max > 5 )); then
 		grep -n . "$f" | grep "^$indent_max_lnum:"
 		echo_error \
-			"bash011 слишком большая глубина(indent=$indent_max), "\
+			"hardbash011 слишком большая глубина(indent=$indent_max), "\
 			"используйте ранний return или сделайте подфункции"
 	fi
 	return 0
 }
 
-bash012(){
+hardbash012(){
 	grep -n '.*|[ ]*[\]$' "$f"  \
-		&& echo_error 'bash012 pipe в "| \" требуется вынести на следующую строку.
+		&& echo_error 'hardbash012 pipe в "| \" требуется вынести на следующую строку.
 	Пример:
 	cat 123 | grep 123 \
 		| while read t; do echo 123; done
@@ -186,14 +191,14 @@ bash012(){
 	return 0
 }
 
-bash013(){
+hardbash013(){
 	grep -n "^[$__SPACE]*#[^ !#{}]." "$f" \
-		&& echo_error 'bash013 ставьте пробел после # или используйте #} #{ для ошибок indent'
+		&& echo_error 'hardbash013 ставьте пробел после # или используйте #} #{ для ошибок indent'
 	return 0
 }
 
 MAX_FSIZE=64
-bash014(){
+hardbash014(){
 	local n=0
 	local fstart=0
 	local fsize=0
@@ -225,50 +230,52 @@ bash014(){
 	done < "$f"
 	[ $fsize_error = TRUE ] \
 		&& echo_error \
-		"bash014 Слишком большая функция больше $MAX_FSIZE строк, "\
+		"hardbash014 Слишком большая функция больше $MAX_FSIZE строк, "\
 		"выделите подфункции __fname"
 	return 0
 }
 
 
-bash015(){
+hardbash015(){
 	fsize=$(cat "$f" | wc -l )
 	fcomm_size=$( grep "^[$__SPACE]*#.*" "$f" | wc -l || true )
 	fcount=$( grep '()[ ]*{' "$f" | wc -l || true ) # ' #}
 	fcount=$(( fcount + 1 ))
 	if (( (fsize-fcomm_size)/fcount > $MAX_FSIZE )); then
 		echo_error \
-			"bash015 Слишком большой линейный файл больше $MAX_FSIZE строк, "\
+			"hardbash015 Слишком большой линейный файл больше $MAX_FSIZE строк, "\
 			"разбейте на функции"
 	fi
 	return 0
 }
-bash016(){
+hardbash016(){
 	egrep -n ".*[$__SPACE]\$" "$f" \
-		&& echo_error 'bash016 Уберите конечные пробелы и tab'
+		&& echo_error 'hardbash016 Уберите конечные пробелы и tab'
 	return 0
 }
 
 MAX_CHARS=100
-bash017(){
+hardbash017(){
 	while IFS='' read -r line; do
 		chars_count=$( echo "$line" | wc -m  || true )
 		if [ $chars_count -gt $MAX_CHARS ]; then
 			echo "$line"
-			echo_error "bash017 длина строки больше $MAX_CHARS используйте перенос \\ "
+			echo_error \
+				"hardbash017 длина строки больше $MAX_CHARS используйте перенос \\ "\
+				"примеры переносов:\necho_suc \"aaaaaaaaaaaaaaaaaa\"\\ \n\"bbbbbbbb\" "
 		fi
 	done < "$f"
 	return 0
 }
 
-bash018(){
+hardbash018(){
 	egrep -n  "^[$__SPACE]*[^#]+.*[^ 0-9)&>$__SPACE]>[ ]*+[^ \$\"'[]+"  "$f" \
-		&& echo_error 'bash018 поставьте пробел перед "text >oo"'
+		&& echo_error 'hardbash018 поставьте пробел перед "text >oo"'
 	return 0
 }
 
 ###
-for check in $( typeset -F | grep bash[0-9][0-9][0-9] | sed 's/declare -f //' || true ); do
+for check in $( typeset -F | grep hardbash[0-9][0-9][0-9] | sed 's/declare -f //' || true ); do
 	$check
 done
 
