Добавлено: утилита сохранения системных файлов в репозитории git

diff --git a/bin/crab_root_autogit b/bin/crab_root_autogit
--- a/bin/crab_root_autogit
+++ b/bin/crab_root_autogit
@@ -3,6 +3,9 @@
 set -eu
 . /opt/crab/crab_utils/bin/::carbon.sys
 
+STORE_SSH_HOST=root@gitlab.carbonsoft.ru
+STORE_PATH=/home/gitlab/root_autogit_repos
+
 
 autogit_install() {
 	if [ -d .git ]; then
@@ -15,6 +18,7 @@ autogit_install() {
 	fi
 
 	[ -d /etc/.git ] && mv /etc/.git /etc/.git_old
+	# TODO: крон задание автогита /etc/.git сносить.
 
 	cat > .gitignore <<EOF
 /*
@@ -56,11 +60,35 @@ autogit_commit() {
 
 autogit_sync() {
 	if git remote | grep -xqm1 origin; then
-		git pull
-		git push
+		# git pull
+		git push origin master:master
 	fi
 	return 0
 }
+
+
+create_remote() {
+	repo_name="$1"
+
+	if ssh $STORE_SSH_HOST [ -d "$STORE_PATH/$repo_name" ]; then
+		echo "Remote directory for repo with name $repo_name already exist." >&2
+		return 1
+	elif [ $? == 255 ]; then
+		echo "Error SSH connect to host $STORE_SSH_HOST." >&2
+		return 2
+	fi
+	ssh $STORE_SSH_HOST git init --bare "$STORE_PATH/$repo_name"
+	return 0
+}
+
+
+git_set_origin() {
+	repo_name="$1"
+
+	git remote add origin "ssh://$STORE_SSH_HOST/$STORE_PATH/$repo_name"
+	return 0
+}
+
 
 sys::usage "$@"
 ### --help Утилита добавление всей корневой файловой системы сервера в git репозиторий.
@@ -72,11 +100,23 @@ sys::usage "$@"
 ### --help crab_root_autogit remove  # удаляет автогит, вместе с репозиторием.
 ### --help Example: crab_root_autogit
 
+
 # работаем только с корнем.
 cd /
 
+
+repo_name=$(hostname)
+
+
 while (( $# > 0 )); do
 	case "${1:-}" in
+	new)
+		create_remote $repo_name
+		autogit_install
+		git_set_origin $repo_name
+		autogit_commit
+		autogit_sync
+		;;
 	install)
 		autogit_install
 		;;
